# Source: tekton-pipeline/templates/feature-flags-cm.yaml
apiVersion: v1
data:
  disable-affinity-assistant: "false"
  disable-creds-init: "false"
  enable-api-fields: alpha
  enable-custom-tasks: "false"
  enable-tekton-oci-bundles: "false"
  require-git-ssh-secret-known-hosts: "false"
  running-in-environment-with-injected-sidecars: "true"
  send-cloudevents-for-runs: "false"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: feature-flags
  namespace: tekton-pipelines
  annotations:
    meta.helm.sh/release-name: 'tekton-pipeline'
