# Source: lighthouse/templates/poller-rb.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lighthouse-poller
  annotations:
    meta.helm.sh/release-name: 'lighthouse'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lighthouse-poller
subjects:
- kind: ServiceAccount
  name: lighthouse-poller
