# Source: lighthouse/templates/poller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse-poller
  labels:
    chart: "lighthouse-1.11.3"
    app: lighthouse-poller
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'lighthouse'
    wave.pusher.com/update-on-config-change: 'true'
  namespace: jx
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: lighthouse-poller
  template:
    metadata:
      annotations:
        ad.datadoghq.com/poller.logs: '[{"source":"lighthouse","service":"poller"}]'
        jenkins-x.io/hash: '7c2d71bfef442eac38ca2d2fac60d3aca77841aa2a86be25e6ec6245b6d2bb91'
      labels:
        app: lighthouse-poller
    spec:
      serviceAccountName: lighthouse-poller
      terminationGracePeriodSeconds: 30
      containers:
      - name: lighthouse-poller
        image: ghcr.io/jenkins-x/lighthouse-poller:1.11.3
        imagePullPolicy: IfNotPresent
        args:
        - "--namespace=jx"
        ports:
        - name: http
          containerPort: 8888
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: http
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        env:
        - name: "GIT_KIND"
          value: "github"
        - name: "GIT_SERVER"
          value: "https://github.com"
        - name: "GIT_USER"
          value: ba11b0y
        - name: "GIT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: lighthouse-oauth-token
              key: oauth
        - name: "HMAC_TOKEN"
          valueFrom:
            secretKeyRef:
              name: lighthouse-hmac-token
              key: hmac
        - name: "JX_LOG_FORMAT"
          value: "json"
        - name: LOG_LEVEL
          value: "info"
        - name: "LOGRUS_FORMAT"
          value: "json"
        - name: LOGRUS_SERVICE
          value: "lighthouse"
        - name: LOGRUS_SERVICE_VERSION
          value: "1.11.3"
        - name: LOGRUS_STACK_SKIP
          value: ""
        - name: POLL_HOOK_ENDPOINT
          value: "http://hook/hook/poll"
        - name: POLL_PERIOD
          value: "20s"
        envFrom:
        - secretRef:
            name: jx-boot-job-env-vars
            optional: true
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
      volumes:
